apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - pv.yaml
  - pvc.yaml
  - secret-provider-class.yaml
  - service.yaml

commonLabels:
  app: nodefront
