
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodefront-page-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
  selector:
    matchLabels:
      usage: nodefront-storage-claim