apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      kind: Ingress
      name: python-app-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: python-app-dev.azurelaboratory.com