apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
spec:
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/rodmhgl/argo_repo_structure
            revision: HEAD
            directories:
              - path: apps/*/envs/dev
        - clusters:
            selector:
              matchLabels:
                environment: dev

  template:
    metadata:
      # name it `<app>-<cluster>`
      name: '{{ regexReplaceAll "apps/(.*)/envs/.*" path "$1" }}-{{ cluster.metadata.name }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rodmhgl/argo_repo_structure
        targetRevision: HEAD
        # this is exactly the folder the git generator gave us
        path: "{{ path }}"
      destination:
        server: "{{ cluster.server }}"
        namespace: '{{ regexReplaceAll "apps/(.*)/envs/.*" path "$1" }}-{{ cluster.metadata.name }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
