apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset-debug
spec:
  generators:
    - git:
        repoURL: https://github.com/rodmhgl/argo_repo_structure
        revision: HEAD
        directories:
          - path: apps/*/envs/dev
  template:
    metadata:
      # Most basic template possible - hardcoded names
      name: 'test-app-1'
    spec:
      project: default
      source:
        repoURL: https://github.com/rodmhgl/argo_repo_structure
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        server: "https://gvku2j2rus-8lu8c1nc.hcp.eastus.azmk8s.io:443"
        namespace: 'test-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true