apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: gcr.io/kuar-demo/kuard-amd64
  newTag: purple # Valid values are: blue, green, or purple
  # newName: gcr.io/kuar-demo/kuard-amd64:blue

patches:
  - target:
      kind: Ingress
      name: kuard
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: kuard.dev.azurelaboratory.com